package example00.interfaces.ws.soap;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.0
 * 2024-03-30T09:03:34.162-03:00
 * Generated source version: 4.0.0
 *
 */
@WebService(targetNamespace = "http://soap.ws.interfaces.example00/", name = "PagoSOAP")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface PagoSOAPcli {

    @WebMethod
    @WebResult(name = "pagos", targetNamespace = "http://soap.ws.interfaces.example00/", partName = "pagos")
    public PagoArray obtenerPagos()
;

    @WebMethod
    @WebResult(name = "idPago", targetNamespace = "http://soap.ws.interfaces.example00/", partName = "idPago")
    public int realizarPago(

        @WebParam(partName = "monto", name = "monto")
        int monto
    );
}
