package example00.interfaces.ws.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.0
 * 2024-03-30T09:03:34.219-03:00
 * Generated source version: 4.0.0
 *
 */
@WebServiceClient(name = "PagoSOAPService",
                  wsdlLocation = "http://localhost:8080/021-JakartaEE-XML/PagoSOAP?wsdl",
                  targetNamespace = "http://soap.ws.interfaces.example00/")
public class PagoSOAPService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soap.ws.interfaces.example00/", "PagoSOAPService");
    public final static QName PagoSOAPPort = new QName("http://soap.ws.interfaces.example00/", "PagoSOAPPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/021-JakartaEE-XML/PagoSOAP?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PagoSOAPService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/021-JakartaEE-XML/PagoSOAP?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PagoSOAPService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PagoSOAPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PagoSOAPService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public PagoSOAPService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PagoSOAPService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PagoSOAPService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns PagoSOAP
     */
    @WebEndpoint(name = "PagoSOAPPort")
    public PagoSOAPcli getPagoSOAPPort() {
        return super.getPort(PagoSOAPPort, PagoSOAPcli.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PagoSOAP
     */
    @WebEndpoint(name = "PagoSOAPPort")
    public PagoSOAPcli getPagoSOAPPort(WebServiceFeature... features) {
        return super.getPort(PagoSOAPPort, PagoSOAPcli.class, features);
    }

}
